version: "3.8"
services:
  davydehaasnl:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    container_name: davydehaasnl
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    expose:
    - 80
    labels:
    - traefik.enable=true
    - traefik.http.routers.davydehaasnl.entrypoints=https
    - traefik.http.routers.davydehaasnl.tls=true
    - traefik.http.routers.davydehaasnl.rule=Host(`davydehaas.nl`)
    - traefik.http.routers.davydehaasnl.middlewares=chain-no-auth@file
    - traefik.http.routers.davydehaasnl.service=davydehaasnl
    - traefik.http.services.davydehaasnl.loadbalancer.server.port=80
    networks:
    - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
