version: "3.7"
services:
  davydehaas.nl:
    image: ${DOCKER_IMAGE}
    container_name: davydehaas.nl
    restart: unless-stopped
    ports:
    - 80:80
    networks:
    - davydehaasnl
networks:
  davydehaasnl:
    driver: bridge
    name: davydehaasnl