version: "3.8"
services:
  davydehaasnl:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    container_name: davydehaasnl
    restart: unless-stopped
    expose:
    - 80
    labels:
    - diun.watch=true
    - traefik.enable=true
    - traefik.http.routers.davydehaasnl.entrypoints=websecure
    - traefik.http.routers.davydehaasnl.rule=Host(`$DOMAIN_NAME`,`www.$DOMAIN_NAME`)
    - traefik.http.routers.davydehaasnl.middlewares=chain-no-auth@file
    - traefik.http.services.davydehaasnl.loadbalancer.server.port=80
    networks:
    - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
