name: Analyse
on:
  push: 
    branches: 
      - develop
jobs:
  analyse:
    name: Analyse
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: Lint fix
        run: npm run lint:fix --if-present
