name: davydehaas.nl develop
on:
  push:
    branches:
      - develop

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

env:
  DOCKER_USERNAME: davydehaas98
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE: davydehaas98/davydehaasnl
  DOCKER_TAG: develop-${{ github.run_number }}-${{ github.run_attempt }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '16.14'
      - name: Clean install dependencies
        run: npm ci
      - name: Test
        run: npm test
        env:
          CI: false
      - name: Build
        run: npm run build --if-present
        env:
          CI: false
      - name: Upload release artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: release-artifact
          path: ./build
      - name: Upload Dockerfile artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: dockerfile-artifact
          path: ./Dockerfile
      - name: Upload NGINX artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: nginx-artifact
          path: ./nginx.conf 
  deliver:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: release-artifact
          path: ./build
      - name: Download Dockerfile artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: dockerfile-artifact
          path: .
      - name: Download NGINX artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: nginx-artifact
          path: .
      - name: Publish Docker image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.DOCKER_REGISTRY }} -u ${{ env.DOCKER_USERNAME }} --password-stdin
          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
