name: develop
on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

env:
  DOCKER_USERNAME: davydehaas98
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE: davydehaas98/davydehaasnl
  DOCKER_TAG: develop-${{ github.run_number }}-${{ github.run_attempt }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Upload build artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: build
          path: ./build
  deliver:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Download build artifact
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          name: build
          path: ./build
      - name: Publish Docker image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.DOCKER_REGISTRY }} -u ${{ env.DOCKER_USERNAME }} --password-stdin
          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
