name: Personal Website
on:
  push:
    branches:
    - main

env:
  DOCKER_CONTAINER: davydehaas.nl
  DOCKER_IMAGE: davydehaas98/davydehaas.nl
  DOCKER_TAG: ${{ github.sha }}
  TARGET_DIRECTORY: ./docker-compose/davydehaas.nl

jobs:
  integrate:
    runs-on: ubuntu-latest
    container:
      image: node:14
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build --if-present
      env:
        CI: false
    - name: Test
      run: npm test
      env:
        CI: false
    - name: Upload release artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-artifact
        path: ./build
    - name: Upload Dockerfile artifact
      uses: actions/upload-artifact@v2
      with:
        name: dockerfile-artifact
        path: ./Dockerfile
    - name: Upload NGINX artifact
      uses: actions/upload-artifact@v2
      with:
        name: nginx-artifact
        path: ./nginx.conf 
  deliver:
    needs: integrate
    runs-on: ubuntu-latest
    steps:
    - name: Download release artifact
      uses: actions/download-artifact@v2
      with:
        name: release-artifact
        path: ./build
    - name: Download Dockerfile artifact
      uses: actions/download-artifact@v2
      with:
        name: dockerfile-artifact
        path: .
    - name: Download NGINX artifact
      uses: actions/download-artifact@v2
      with:
        name: nginx-artifact
        path: .
    - name: Publish Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
        docker build -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .
        docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG}}
  deploy:
    needs: deliver
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SSH SCP | Copy docker-compose.yml
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "docker-compose.yml"
        target: ${{ env.TARGET_DIRECTORY }}
    - name: SSH | Start container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ env.TARGET_DIRECTORY }}
          echo 'DOCKER_IMAGE=${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}' > .env
          docker-compose -f docker-compose.yml down --rmi all
          docker-compose -f docker-compose.yml up -d 
